### ISSUE TITLE
ftrack connect wont launch dynamic env hook

### ISSUE THREAD

**Issue by antirotor** [antirotor/magiclab-pipeline#2]
ftrack connect is totally ignoring dynamic_env skeleton hook for modifying application environmnet before launch. I hooked it on ftrack,acion.launch or ftrack.connect.application.launch

**Comment by jezschaj** [comment]
presume this is the resulting issue of the bug, isn't it?
`Nuke 10.5v1, 64 bit, built Dec  6 2016.
Copyright (c) 2016 The Foundry Visionmongers Ltd.  All Rights Reserved.
Licence expires on: 2018/1/2
- plugin workgroup for major version 10 is  [ Nuke10.5 ]
Traceback (most recent call last):
  File "C:\Users\jakub.jezek\Documents\GitHub\magiclab-pipeline\externals\development\python_modules\ftrack_connect\resource\ftrack_connect_nuke\nuke_path/menu.py", line 5, in <module>
    import ftrack_connect_nuke
  File "C:\Users\jakub.jezek\Documents\GitHub\magiclab-pipeline\externals\development\python_modules\ftrack_connect_nuke\__init__.py", line 6, in <module>
    import ftrack_connect_nuke.plugin
  File "C:\Users\jakub.jezek\Documents\GitHub\magiclab-pipeline\externals\development\python_modules\ftrack_connect_nuke\plugin.py", line 4, in <module>
    import ftrack_connect_foundry.plugin
ImportError: No module named ftrack_connect_foundry.plugin`

**Comment by jezschaj** [comment]
cuzz, jenom rychly report..

1. myslim ze jsem opravil ty navaznosti na dynamic_env ale je potreba to
proverit.
2. nasel jsem asi duvod proc se nam nespousti ten hook na nuke open. chyby
navaznost kdesy v ftrack-connect modulu, ktera by odkazovala do:
..\magiclab-pipeline\externals\development\python_modules\ftrack_connect\resource\connect-standard-plugins
>> tam jsou totiz veskere dalsi navaznosti
3. doplnil jsem nejake slozky do PIPELINE (image,
template_folder_structure, sudio_repos)
4. potrebuju se pridat jako contributora do
https://github.com/antirotor/connect_magiclab/tree/master/connect_magiclab
>> chtel bych commitnout nejake zmeny do __main__.py
5. nastavil jsem testovaci magiclab_vfx.yml a snad opravil spravne moduly
ktere jsou zodpovedne za cteni lucidity/yml - a cesty na ne

- to je asi vse.. ale mozna mi neco vypadlo.. u me doma se mi to uz spousti
o te doby co byly opravedny ty cesty odkazujici na tvrdo do V:\.. pro ten
dynamic_env (tedy myslim ze to byl ten problem :)) (porad si nejsem jisty
jestli to spravne chapu.. D)
- osobne si myslim, ze ta struktra development pipeline by se dala
zjednodusit, tak aby bylo jasne co jsou pyblish_pluginy a co support_moduly
>> ted je to rozhazene do ftrack_connect atd.. restpective ne vsechny
validate/colect/extrack ppluginy jsou ve slozce pyblish/plugins a tim se to
cele zneprehlednuje

napis prosim co si o tom myslis? diky :) zatim cuzz a Stastne a Vesele!!!

J.

JAKUB JEŽEK
grading, compositing, online
+420 775 115 173

*MAGICLAB*

Oldřichova 36
<https://maps.google.com/?q=Old%C5%99ichova+36128+00+Praha+2+Czech+Republic&entry=gmail&source=g>
128 00 Praha 2
<https://maps.google.com/?q=Old%C5%99ichova+36128+00+Praha+2+Czech+Republic&entry=gmail&source=g>
Czech Republic
<https://maps.google.com/?q=Old%C5%99ichova+36128+00+Praha+2+Czech+Republic&entry=gmail&source=g>

jakub.jezek@magiclab.cz
www.magiclab.cz
